service: signup
runtime: go113
main: ./cmd/gformd
env_variables:
#  GODEBUG: http2debug=2
#  GRPC_GO_LOG_VERBOSITY_LEVEL: 99
#  GRPC_GO_LOG_SEVERITY_LEVEL: info
#   GRPC_GO_REQUIRE_HANDSHAKE: "off"
#   # GODEBUG: "netdns=2"
#   # HOSTALIASES: "/srv/hosts-override"
